"""empty message

Revision ID: 225dfed6e63d
Revises: cbaf4be1f16f
Create Date: 2023-09-27 00:15:13.512115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '225dfed6e63d'
down_revision = 'cbaf4be1f16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courseenrollment', schema=None) as batch_op:
        batch_op.drop_column('id_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courseenrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
