"""empty message

Revision ID: 91255c98b688
Revises: c24afcc757d9
Create Date: 2023-09-22 21:15:43.696420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91255c98b688'
down_revision = 'c24afcc757d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenblocked', schema=None) as batch_op:
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenblocked', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
