"""empty message

Revision ID: abdcf39a047c
Revises: 42662b25b873
Create Date: 2023-09-11 22:12:36.069242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abdcf39a047c'
down_revision = '42662b25b873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
