"""empty message

Revision ID: c7d31470987f
Revises: a937c996b668
Create Date: 2023-09-08 15:52:09.955682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d31470987f'
down_revision = 'a937c996b668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addcourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=200), nullable=False),
    sa.Column('finish_date', sa.String(length=200), nullable=False),
    sa.Column('contents', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('contents'),
    sa.UniqueConstraint('cost'),
    sa.UniqueConstraint('course'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('finish_date'),
    sa.UniqueConstraint('modality'),
    sa.UniqueConstraint('provider'),
    sa.UniqueConstraint('start_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addcourse')
    # ### end Alembic commands ###
