"""empty message

Revision ID: f1b5e9103316
Revises: 56b6441dbea9
Create Date: 2023-09-09 22:32:36.915080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1b5e9103316'
down_revision = '56b6441dbea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=200), nullable=False),
    sa.Column('finish_date', sa.String(length=200), nullable=False),
    sa.Column('contents', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('contents'),
    sa.UniqueConstraint('cost'),
    sa.UniqueConstraint('course'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('finish_date'),
    sa.UniqueConstraint('modality'),
    sa.UniqueConstraint('provider'),
    sa.UniqueConstraint('start_date')
    )
    with op.batch_alter_table('addcourse', schema=None) as batch_op:
        batch_op.drop_index('category')
        batch_op.drop_index('code')
        batch_op.drop_index('contents')
        batch_op.drop_index('cost')
        batch_op.drop_index('course')
        batch_op.drop_index('description')
        batch_op.drop_index('finish_date')
        batch_op.drop_index('modality')
        batch_op.drop_index('provider')
        batch_op.drop_index('start_date')

    op.drop_table('addcourse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addcourse',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('cost', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('modality', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('start_date', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('finish_date', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('contents', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('addcourse', schema=None) as batch_op:
        batch_op.create_index('start_date', ['start_date'], unique=False)
        batch_op.create_index('provider', ['provider'], unique=False)
        batch_op.create_index('modality', ['modality'], unique=False)
        batch_op.create_index('finish_date', ['finish_date'], unique=False)
        batch_op.create_index('description', ['description'], unique=False)
        batch_op.create_index('course', ['course'], unique=False)
        batch_op.create_index('cost', ['cost'], unique=False)
        batch_op.create_index('contents', ['contents'], unique=False)
        batch_op.create_index('code', ['code'], unique=False)
        batch_op.create_index('category', ['category'], unique=False)

    op.drop_table('course')
    # ### end Alembic commands ###
